### ISSUE TITLE
every Map that uses SharpCraft dont run!

### ISSUE THREAD

**Issue by MasterHK** [TinkerWorX/SharpCraft#27]
When i press start when i have that map selected on my list (in the Single Player/Custom Game) game revert to list and loading doesn't appear...

it's my [debug.log](https://gist.github.com/MasterHK/c9c1c6275b7289e98b97527eaf9cea8e)
I have 1.26.0.6401 and Win 7 x64 SP1 with latest version of SharpCraft.

have i totally need to include an specified common.j in my map?

even maps that i've downloaded from [this thread](http://www.hiveworkshop.com/threads/custom-jass-natives-requests-submissions.244688/) have this problem...

**Comment by TinkerWorX** [comment]
The log doesn't show any natives added. Are you mixing old plugins with a newer SharpCraft?

**Comment by MasterHK** [comment]
old plugins? may, but i only downloaded [plugins.zip](http://www.hiveworkshop.com/attachments/plugins-zip.131056/) from [above thread](http://www.hiveworkshop.com/threads/custom-jass-natives-requests-submissions.244688/).
I even i've tried [Extract-Play.zip](http://www.hiveworkshop.com/attachments/extract-play-zip.131058/) but without any result...

I just downloaded latest release (v4.0.0.152) from here and the same result remains...

However, i attach my [settings.xml](https://uploadfiles.io/3d556) (it's quite untouched) in case i think it  have incorrect adresses to hook the program.

**Comment by MasterHK** [comment]
I just have noticed the new [debug.log](https://gist.github.com/MasterHK/4fbc240a077e6f286064218cd6a8e8ab) with the clear version of SharpCraft (only with [plugins.zip](http://www.hiveworkshop.com/attachments/plugins-zip.131056/)).

**Comment by triggerhappy187** [comment]
Those are the wrong plugins. They are old.

http://www.hiveworkshop.com/threads/sharpcraft-a-managed-replacement-for-reinventing-the-craft.244317/

The correct ones are in the second post in the link above.

**Comment by MasterHK** [comment]
Are all of the old natives exists in the new ones?

**Comment by MasterHK** [comment]
This is my debug.log and it seems everything is just fine.
>     Native added: StopwatchGet()I
>     Native added: StopwatchFree(I)V
>     Native added: StopwatchElapsedMilliseconds(I)R
>     Native added: StopwatchElapsedSeconds(I)R

But I have 2 questions:
1- Are old natives implemented for this version?
2- Can SC compile .cs files at runtime (as mentioned [here](http://www.hiveworkshop.com/threads/custom-jass-natives-requests-submissions.244688/page-7#post-2592568))?

**Comment by TinkerWorX** [comment]
SharpCraft doesn't come with any natives. It is purely a plugin system for Warcraft III. None of the standard plugins in the post on The Hive Workshop come with any natives either, only a framework to add your own natives. If you want custom natives, you can take a look at the natives mentioned by @triggerhappy187. SC doesn't compile .cs at runtime anymore to make everything simpler. You can find a tutorial on how to make plugins on The Hive Workshop.

**Comment by MasterHK** [comment]
I already know that SharpCraft doesn't have "native" natives :D
I just try to escape from VS Environment for now (don't get confused with programming/coding please... :) )...

...hence can I ask you what's latest release that supports old plugins / self compiling ?

**Comment by TinkerWorX** [comment]
You will have to look back through the versions. Runtime-compiling of C# turned out to be rather messy, which is why it was removed. If you make an issue with a request for runtime-compiling I might be able to make a plugin to handle it.
